/* Charts and audio traces for "Comparing turn-taking in GPT-Live-1 and gpt-realtime-2.1".
   Reads window.DATA (data.js, generated by turnprobe scripts/build_post2_data.py). Every value a
   tooltip shows is also in the figure's data table. */

(function () {
  "use strict";
  var DATA = window.DATA;
  if (!DATA) return;

  var NS = "http://www.w3.org/2000/svg";
  function S(tag, attrs, parent) {
    var e = document.createElementNS(NS, tag);
    for (var k in attrs) e.setAttribute(k, attrs[k]);
    if (parent) parent.appendChild(e);
    return e;
  }
  function T(tag, attrs, text, parent) { var e = S(tag, attrs, parent); e.textContent = text; return e; }
  function H(tag, cls, text) { var e = document.createElement(tag); if (cls) e.className = cls; if (text != null) e.textContent = text; return e; }
  function secs(ms, d) { return (ms / 1000).toFixed(d == null ? 2 : d) + " s"; }

  var SYS = {
    server:   { label: "gpt-realtime · server_vad", color: "var(--s-server)" },
    sem_high: { label: "gpt-realtime · semantic high", color: "var(--s-high)" },
    sem_auto: { label: "gpt-realtime · semantic auto", color: "var(--s-auto)" },
    sem_low:  { label: "gpt-realtime · semantic low", color: "var(--s-low)" },
    live:     { label: "GPT-Live-1", color: "var(--s-live)" }
  };
  var ORDER = DATA.order;

  // ------------------------------------------------------------- shared chrome
  var tip = document.getElementById("tip");
  function showTip(evt, title, rows) {
    tip.replaceChildren(H("div", "t", title));
    rows.forEach(function (r) {
      var row = H("div", "r");
      if (r.color) { var i = H("i"); i.style.background = r.color; row.appendChild(i); }
      row.appendChild(H("b", null, r.value));
      if (r.label) row.appendChild(H("span", null, r.label));
      tip.appendChild(row);
    });
    tip.hidden = false;
    var w = tip.offsetWidth, h = tip.offsetHeight, x = evt.clientX + 14, y = evt.clientY + 14;
    if (x + w > innerWidth - 8) x = evt.clientX - w - 14;
    if (y + h > innerHeight - 8) y = evt.clientY - h - 14;
    tip.style.left = x + "px"; tip.style.top = y + "px";
  }
  function hideTip() { tip.hidden = true; }
  function hover(el, title, rows) {
    el.addEventListener("pointermove", function (evt) { showTip(evt, title, rows); });
    el.addEventListener("pointerleave", hideTip);
  }
  function legend(items) {
    var el = H("div", "legend");
    items.forEach(function (it) {
      var s = H("span"), i = H("i", it.kind); i.style.background = it.color;
      s.appendChild(i); s.appendChild(document.createTextNode(it.label)); el.appendChild(s);
    });
    return el;
  }
  function dataTable(head, rows) {
    var d = H("details"), sum = H("summary", null, "Data table"), wrap = H("div", "dtable"), t = H("table");
    var tr = H("tr"); head.forEach(function (h) { tr.appendChild(H("th", null, h)); });
    var th = H("thead"); th.appendChild(tr); t.appendChild(th);
    var tb = H("tbody");
    rows.forEach(function (r) { var row = H("tr"); r.forEach(function (c) { row.appendChild(H("td", null, String(c))); }); tb.appendChild(row); });
    t.appendChild(tb); wrap.appendChild(t); d.appendChild(sum); d.appendChild(wrap);
    return d;
  }
  function mount(fig, nodes) {
    var cap = fig.querySelector("figcaption");
    nodes.forEach(function (n) { fig.insertBefore(n, cap); });
  }
  function axis(svg, x, Tp, bottom, xmax, step, fmt) {
    for (var v = 0; v <= xmax + 1e-9; v += step) {
      S("line", { x1: x(v), x2: x(v), y1: Tp, y2: bottom, "class": v === 0 ? "ax" : "gl" }, svg);
      T("text", { x: x(v), y: bottom + 15, "text-anchor": "middle", "class": "tx" }, fmt(v), svg);
    }
  }

  // ------------------------------------------------------------- speech before the caller finished
  (function () {
    var fig = document.getElementById("fig-early");
    if (!fig) return;
    fig.classList.add("viz");
    var kinds = [["incomplete", "Unfinished clause"], ["dictation", "Dictation"], ["complete", "First half sounds complete"]];
    var W = 960, L = 230, R = 70, rowH = 26, panelGap = 30, Tp = 8, B = 34, bar = 16;
    var Hh = Tp + kinds.length * (ORDER.length * rowH + panelGap) + B;
    function x(v) { return L + v * (W - L - R); }
    var svg = S("svg", { viewBox: "0 0 " + W + " " + Hh, role: "img", "aria-label": "Share of trials where the model spoke before the caller finished, by sentence kind" });
    var bottom = Hh - B;
    axis(svg, x, Tp, bottom, 1, 0.25, function (v) { return Math.round(v * 100) + "%"; });
    var rows = [], y = Tp;
    kinds.forEach(function (kd) {
      y += panelGap;
      T("text", { x: 0, y: y - 10, "class": "tx" }, kd[1].toUpperCase(), svg);
      ORDER.forEach(function (key) {
        var c = DATA.early[key][kd[0]], cy = y + rowH / 2, top = cy - bar / 2;
        T("text", { x: 0, y: cy + 4, "class": "dl" }, SYS[key].label, svg);
        S("rect", { x: x(0), y: top, width: x(1) - x(0), height: bar, fill: "var(--rule)", opacity: 0.35, rx: 2 }, svg);
        var ack = c.ack / c.n, rep = c.reply / c.n;
        var a = S("rect", { x: x(0), y: top, width: Math.max(0, x(ack) - x(0)), height: bar, fill: "var(--ack)" }, svg);
        var r = S("rect", { x: x(ack) + (ack > 0 ? 2 : 0), y: top, width: Math.max(0, x(ack + rep) - x(ack) - (ack > 0 ? 2 : 0)), height: bar, fill: "var(--model)" }, svg);
        var title = SYS[key].label + " · " + kd[1];
        var tipRows = [{ color: "var(--ack)", value: c.ack + "/" + c.n, label: "only a short acknowledgment" },
                       { color: "var(--model)", value: c.reply + "/" + c.n, label: "started a reply" }];
        hover(a, title, tipRows); hover(r, title, tipRows);
        T("text", { x: x(ack + rep) + 6, y: cy + 4, "class": "dl2" }, (c.ack + c.reply) + "/" + c.n, svg);
        rows.push([SYS[key].label, kd[1], c.n, c.ack, c.reply]);
        y += rowH;
      });
    });
    T("text", { x: (L + W - R) / 2, y: Hh - 3, "text-anchor": "middle", "class": "at" }, "share of trials where the model spoke before the caller finished", svg);
    var wrap = H("div"); wrap.appendChild(svg);
    mount(fig, [legend([{ kind: "kr", color: "var(--ack)", label: "Only a short acknowledgment (“Got it”, “Mm-hmm”, “Okay”)" },
                        { kind: "kr", color: "var(--model)", label: "Started a reply" }]), wrap]);
    fig.appendChild(dataTable(["System", "Sentence", "Trials", "Acknowledgment only", "Started a reply"], rows));
  })();

  // ------------------------------------------------------------- reply-gap strip
  (function () {
    var fig = document.getElementById("fig-waits");
    if (!fig) return;
    fig.classList.add("viz");
    var W = 960, rowH = 68, L = 230, R = 24, Tp = 24, B = 40;
    var Hh = Tp + ORDER.length * rowH + B;
    var xmax = Math.ceil(Math.max.apply(null, ORDER.map(function (k) { return DATA.gaps[k].max; })) / 1000) * 1000;
    function x(v) { return L + v / xmax * (W - L - R); }
    var svg = S("svg", { viewBox: "0 0 " + W + " " + Hh, role: "img", "aria-label": "Reply gap per trial by system" });
    axis(svg, x, Tp - 6, Hh - B, xmax, 1000, function (v) { return v / 1000 + " s"; });
    T("text", { x: (L + W - R) / 2, y: Hh - 5, "text-anchor": "middle", "class": "at" }, "silence from the end of the caller's sentence to the first audible reply", svg);
    ORDER.forEach(function (key, i) {
      var cy = Tp + i * rowH + rowH / 2, g = DATA.gaps[key];
      S("circle", { cx: 8, cy: cy - 4, r: 4.5, fill: SYS[key].color }, svg);
      T("text", { x: 20, y: cy, "class": "dl", style: key === "live" ? "font-weight:600" : "" }, SYS[key].label, svg);
      g.values.forEach(function (v, j) {
        var jit = ((j * 7919) % 23 - 11) * 1.1;
        S("circle", { cx: x(v), cy: cy + jit, r: 3.4, fill: SYS[key].color, stroke: "var(--paper-2)", "stroke-width": 1.3 }, svg);
        hover(S("circle", { cx: x(v), cy: cy + jit, r: 8, fill: "transparent" }, svg), SYS[key].label, [{ color: SYS[key].color, value: secs(v), label: "one trial" }]);
      });
      S("line", { x1: x(g.p50), x2: x(g.p50), y1: cy - 18, y2: cy + 18, stroke: "var(--ink)", "stroke-width": 2 }, svg);
      T("text", { x: x(g.p50), y: cy - 22, "text-anchor": "middle", "class": "dl" }, "p50 " + secs(g.p50), svg);
      S("circle", { cx: x(g.p90), cy: cy + 20, r: 4, fill: "var(--paper-2)", stroke: "var(--ink)", "stroke-width": 1.5 }, svg);
      T("text", { x: x(g.p90) + 8, y: cy + 24, "class": "dl2" }, "p90 " + secs(g.p90), svg);
    });
    var wrap = H("div"); wrap.appendChild(svg);
    mount(fig, [wrap]);
    fig.appendChild(dataTable(["System", "Trials with a reply", "p10", "Median", "p90", "Max"], ORDER.map(function (k) {
      var g = DATA.gaps[k]; return [SYS[k].label, g.n, secs(g.p10), secs(g.p50), secs(g.p90), secs(g.max)];
    })));
  })();

  // ------------------------------------------------------------- fragments table
  (function () {
    var host = document.getElementById("fig-fragments");
    if (!host) return;
    var keys = ["sem_low", "sem_auto", "live"], stims = [["capital", "Can you tell me what the capital of … Australia is?"], ["weather", "What's the weather going to be like in … Seattle this weekend?"]];
    var t = H("table"), head = H("tr");
    ["Sentence", "Voice", "System", "Whole sentence", "Second half alone", "Split with a 1.5 s pause"].forEach(function (h) { head.appendChild(H("th", null, h)); });
    var th = H("thead"); th.appendChild(head); t.appendChild(th);
    var tb = H("tbody");
    stims.forEach(function (st) {
      ["coral", "ash"].forEach(function (v) {
        keys.forEach(function (k) {
          var c = (DATA.fragments[k] || {})[st[0] + "/" + v] || {}, tr = H("tr");
          if (k === "live") tr.className = "hi";
          [st[1], v, SYS[k].label].forEach(function (x) { tr.appendChild(H("td", null, x)); });
          ["whole", "b_alone", "split"].forEach(function (cond) {
            tr.appendChild(H("td", "num", c[cond] == null ? "–" : secs(c[cond], 1)));
          });
          tb.appendChild(tr);
        });
      });
    });
    t.appendChild(tb); host.appendChild(t);
  })();

  // ------------------------------------------------------------- stopping
  (function () {
    var fig = document.getElementById("fig-stop");
    if (!fig) return;
    fig.classList.add("viz");
    var keys = ["server", "sem_auto", "live"], groups = [["backchannel", "Backchannel (“mm-hm”, “yeah”, “okay”, “right, right”)"], ["interrupt", "Interruption (“wait, stop”, a question)"]];
    var W = 960, L = 230, R = 170, rowH = 34, gap = 34, Tp = 8, B = 36;
    var Hh = Tp + groups.length * (keys.length * rowH + gap) + B, xmax = 2500;
    function x(v) { return L + Math.min(v, xmax) / xmax * (W - L - R); }
    var svg = S("svg", { viewBox: "0 0 " + W + " " + Hh, role: "img", "aria-label": "Time for the model to stop talking after the caller started, by system" });
    axis(svg, x, Tp, Hh - B, xmax, 500, function (v) { return v / 1000 + " s"; });
    T("text", { x: (L + W - R) / 2, y: Hh - 3, "text-anchor": "middle", "class": "at" }, "time from the caller starting to talk until the model's audio stops", svg);
    var rows = [], y = Tp;
    groups.forEach(function (g) {
      y += gap;
      T("text", { x: 0, y: y - 10, "class": "tx" }, g[1].toUpperCase(), svg);
      keys.forEach(function (key) {
        var rs = DATA.overlap.filter(function (r) { return r.system === key && r.kind === g[0]; });
        var stopped = rs.filter(function (r) { return r.outcome !== "kept_talking" && r.stop_latency_ms != null; });
        var kept = rs.length - stopped.length, cy = y + rowH / 2;
        T("text", { x: 0, y: cy + 4, "class": "dl", style: key === "live" ? "font-weight:600" : "" }, SYS[key].label, svg);
        stopped.forEach(function (r, j) {
          var jit = ((j * 7919) % 13 - 6) * 1.2;
          S("circle", { cx: x(r.stop_latency_ms), cy: cy + jit, r: 4.2, fill: SYS[key].color, stroke: "var(--paper-2)", "stroke-width": 1.5 }, svg);
          hover(S("circle", { cx: x(r.stop_latency_ms), cy: cy + jit, r: 9, fill: "transparent" }, svg), SYS[key].label + " · “" + DATA.meta.clips[r.clip].text + "” · voice " + r.voice,
                [{ color: SYS[key].color, value: Math.round(r.stop_latency_ms) + " ms", label: "to stop" }]);
        });
        T("text", { x: W - R + 12, y: cy + 4, "class": "dl2" }, kept ? "kept talking " + kept + "/" + rs.length : "stopped " + stopped.length + "/" + rs.length, svg);
        rows.push([SYS[key].label, g[0], rs.length, stopped.length, kept, stopped.map(function (r) { return Math.round(r.stop_latency_ms); }).sort(function (a, b) { return a - b; }).join(", ")]);
        y += rowH;
      });
    });
    var wrap = H("div"); wrap.appendChild(svg);
    mount(fig, [wrap]);
    fig.appendChild(dataTable(["System", "Clip type", "Trials", "Stopped", "Kept talking", "Time to stop (ms)"], rows));
  })();

  // ------------------------------------------------------------- audio traces
  (function () {
    var byName = {};
    DATA.examples.forEach(function (e) { byName[e.name] = e; });
    var colors = { m: "var(--model)", u: "var(--user)" };
    Array.prototype.forEach.call(document.querySelectorAll("figure.trace"), function (fig) {
      var e = byName[fig.getAttribute("data-example")];
      if (!e) return;
      var w0 = e.window[0], w1 = e.window[1];
      var top = H("div", "tr-top");
      top.appendChild(H("span", "tr-title", e.title));
      top.appendChild(H("span", "tr-sub", e.sub));
      fig.appendChild(top);

      var W = 960, L = 60, R = 10, Hh = 212, lanes = { u: [12, 68], m: [128, 184] };
      function x(t) { return L + (t - w0) / (w1 - w0) * (W - L - R); }
      var svg = S("svg", { viewBox: "0 0 " + W + " " + Hh, role: "img", "aria-label": "Recorded caller and model audio with numbered events", "class": "viz" });
      T("text", { x: 0, y: 44, "class": "lane" }, "CALLER", svg);
      T("text", { x: 0, y: 160, "class": "lane" }, "MODEL", svg);
      function env(arr, lane, cls) {
        var mid = (lane[0] + lane[1]) / 2, half = (lane[1] - lane[0]) / 2, step = 20;
        var i0 = Math.max(0, Math.floor(w0 / step)), i1 = Math.min(arr.length - 1, Math.ceil(w1 / step));
        var topPath = "", bot = [];
        for (var i = i0; i <= i1; i++) {
          var px = x(i * step).toFixed(1), a = Math.max(0.015, arr[i]) * half;
          topPath += (i === i0 ? "M" : "L") + px + "," + (mid - a).toFixed(1);
          bot.push(px + "," + (mid + a).toFixed(1));
        }
        S("path", { d: topPath + "L" + bot.reverse().join("L") + "Z", "class": cls }, svg);
      }
      env(e.user, lanes.u, "env-u");
      env(e.model, lanes.m, "env-m");
      S("line", { x1: L, x2: W - R, y1: 194, y2: 194, "class": "ax" }, svg);
      for (var t = w0; t <= w1; t += 1000) T("text", { x: x(t), y: 208, "text-anchor": "middle", "class": "tx" }, ((t - w0) / 1000) + " s", svg);
      var prev = -Infinity;
      e.items.forEach(function (it, i) {
        var tx = x(it[0]), dx = Math.max(tx, prev + 21);
        prev = dx;
        S("line", { x1: tx, x2: tx, y1: lanes.u[0], y2: lanes.m[1], "class": "mark" }, svg);
        if (dx !== tx) S("line", { x1: tx, x2: dx, y1: 98, y2: 98, "class": "mark" }, svg);
        S("circle", { cx: dx, cy: 98, r: 9, fill: colors[it[1]], stroke: "var(--paper-2)", "stroke-width": 2 }, svg);
        T("text", { x: dx, y: 101.5, "class": "evn", fill: it[1] === "m" ? "#1A201E" : "#fff" }, String(i + 1), svg);
      });
      var head = S("line", { x1: x(w0), x2: x(w0), y1: 6, y2: 194, "class": "head", visibility: "hidden" }, svg);
      fig.appendChild(svg);

      var body = H("div", "tr-body"), left = H("div"), right = H("div");
      var audio = H("audio"); audio.controls = true; audio.preload = "none"; audio.src = "audio/" + e.name + ".mp3";
      audio.addEventListener("timeupdate", function () {
        var ms = w0 + audio.currentTime * 1000;
        if (ms >= w0 && ms <= w1) { head.setAttribute("x1", x(ms)); head.setAttribute("x2", x(ms)); head.setAttribute("visibility", "visible"); }
        else head.setAttribute("visibility", "hidden");
      });
      left.appendChild(audio);
      var ol = H("ol", "ev");
      e.items.forEach(function (it, i) {
        var li = H("li"), n = H("span", "n", String(i + 1));
        n.style.background = colors[it[1]]; if (it[1] === "m") n.style.color = "#1A201E";
        li.appendChild(n); li.appendChild(H("span", "t", secs(it[0] - w0))); li.appendChild(H("span", null, it[2]));
        ol.appendChild(li);
      });
      left.appendChild(ol);
      var said = H("div", "said");
      e.said.forEach(function (s) { said.appendChild(H("div", "who", s[0])); said.appendChild(H("p", null, s[1])); });
      right.appendChild(said);
      right.appendChild(H("div", "take", e.take));
      body.appendChild(left); body.appendChild(right);
      fig.appendChild(body);
    });
  })();
})();
